name: Upgrade Gradle wrapper on all projects

on:
  workflow_dispatch:
    inputs:
      gradle-version:
        description: Enter the Gradle version
        required: true

jobs:
  upgrade_wrapper:
    name: Upgradle wrapper on all
    runs-on: ubuntu-latest
    strategy:
      matrix:
          git-repo: ['git@github.com:alextu/gradle-playground.git', 'git@github.com:alextu/gradle-playground.git']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        #with:
        #  repository: alextu/gradle-wrapper-upgrader
        #  ref: main
        #  token: ${{ secrets.CCUD_GIT_TOKEN }}
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Upgrade wrapper
        uses: gradle/gradle-build-action@v2
        env:
          GRADLE_PROJECT_gitUrl: ${{ matrix.git-repo }}
          GRADLE_PROJECT_gradleVersion: ${{ github.event.inputs.gradle-version }}
        with:
          arguments: clean upgradeWrapper gitPush