name: Upgrade Gradle wrapper on all projects

on:
  workflow_dispatch:
    inputs:
      gradle-version:
        description: Enter the Gradle version
        required: true

jobs:
  upgrade_wrapper:
    name: Upgradle wrapper on all
    runs-on: ubuntu-latest
    strategy:
      matrix:
          git-repo: ['https://github.com/alextu/gradle-playground.git','https://github.com/alextu/gradle-playground2.git']
    steps:
      - name: Checkout gradle-wrapper-upgrader
        uses: actions/checkout@v2
        # with:
        #  repository: alextu/gradle-wrapper-upgrader
        #  ref: main
      # - name: Import GPG key
      #   uses: crazy-max/ghaction-import-gpg@v4
      #   with:
      #     gpg_private_key: ${{ secrets.SOME_PGP_PRIVATE_KEY }}
      #     passphrase: ${{ secrets.SOME_PGP_PASSPHRASE }}
      #     git_user_signingkey: true
      #     git_commit_gpgsign: true
      - name: Setup git config
        env:
          TOKEN: ${{ secrets.CCUD_GIT_TOKEN }}
        run: |
          git config --global user.name "bot-githubaction"
          git config --global user.email "bot-githubaction@gradle.com"
          git config --global url."https://${TOKEN}:x-oauth-basic@github.com/".insteadOf "https://github.com/"

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Upgrade wrapper
        uses: gradle/gradle-build-action@v2
        env:
          ORG_GRADLE_PROJECT_gitUrl: ${{ matrix.git-repo }}
          ORG_GRADLE_PROJECT_gradleVersion: ${{ github.event.inputs.gradle-version }}
        with:
          arguments: clean upgradeWrapper gitPush